# Dependabot configuration for SystemF Software monorepo
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Dev Container updates
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # Root workspace dependencies (pnpm workspace)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      nx:
        patterns:
          - "@nx/*"
          - "nx"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
